### PR TITLE
feat(ida-18): Initial project structure and dockerization done

### PR DESCRIPTION
**Pull request by maqboolkhan**

### CODE REVIEW

**Comment by MichaelRoeder** [comment]
You may want to think about adding a file defining formatting rules. Especially if you use different IDEs and/or different OS within the project, something like an .editorconfig file defining which line endings to use comes in handy.

**Comment by RicardoUsbeck** [comment]
How about the .mvn folder. Shouldn't that go to the .gitignore as well?

**Comment by maqboolkhan** [comment]
> How about the .mvn folder. Shouldn't that go to the .gitignore as well?

Actually I was also thinking the same but I could not find anywhere that if we can put the whole `.mvn` folder in `.gitignore`.

**Comment by RicardoUsbeck** [comment]
> > How about the .mvn folder. Shouldn't that go to the .gitignore as well?
> 
> Actually I was also thinking the same but I could not find anywhere that if we can put the whole `.mvn` folder in `.gitignore`.

`.mvn/`

**Comment by maqboolkhan** [comment]
Closing this PR because of the following reasons:
1. We have different strategies for branches. It will reflect how we manage stories over JIRA

**Pull request closed without merging**
