### PR TITLE
Rdf dataconversion

### PR DESCRIPTION
**Pull request by AsjadLFC**
- [x] Two Literature tables.
- [x] Analyse if all the fields found in DB tables have been covered in Ontology design.
- [x] deathPlace & birthPlace as Resources instead of strings, use existing publically available Place resources from DBPedia.
- [x] Use foaf ontology, the soldier should be a type of foaf: Person, also analyze and reuse properties like lastName/firstName available in foaf.
- [x] Add German language labels for classes.
- [x] Changing the URL prefix.
- [x] Troubleshoot the problem with special characters in the output TTL file.
- [x] Remove Soldier resources with names in URI, only use ids. Possibly do this for other resources as well.
- [x] Introduce more subclasses in the Ontology for correct assignment of data properties
- [x] Discussion: Removing classes starting with _ as suggested by Adrian.

### CODE REVIEW

**Comment by maqboolkhan** [comment]
Hi @AsjadLFC @tohardik,
Good Work 👍 but you guys committed `ttl file of classified data` please remove it asap

**Comment by tohardik** [comment]
@maqboolkhan I just checked and confirm that the ttl files have only ontology definitions (no sensitive data). I was instructed to keep versioned files of ontology definition checked-into the repository.

**Comment by tohardik** [comment]
@Cortys check this out https://support.codacy.com/hc/en-us/articles/360005097654-Ignore-files-from-Codacy-analysis
It is possible to ignore one file from Codacy check. But I am not seeing the "Settings" option when I open ida's Codacy page. Perhaps I do not have access to it. Can you please check?

**Comment by Cortys** [comment]
@tohardik You are right, Codacy is currently set up via @nikit91's account so we cannot reconfigure it. We should probably use a Codacy [organization](https://support.codacy.com/hc/en-us/articles/360009209594-Creating-and-renaming-an-organization) instead to allow multiple team members to change settings. @nikit91 what do you think?

For your specific problem however, the `.codacy.yaml` configuration file should also allow you to exclude files via the `exclude_paths` property. Maybe try that first.

**Comment by nikit91** [comment]
@Cortys I believe the problem is solved for now, but yes we need to start using the codacy organization. I will try to get this project added to the DICE group's codacy.

**Comment by maqboolkhan** [comment]
@tohardik @AsjadLFC this PR is ready to be merged but i remember Definition files` were committed into the `Git` and now you have removed them I just want to ask have you guys removed them from Git history as well? 
After removing them from Git history kindly comment here so we will merge this PR

Best

**Comment by tohardik** [comment]
@maqboolkhan the purging from history is done. The branch is clean now. You can go ahead with merging.

**Comment by tohardik** [comment]
@Cortys I contacted the support team and they've fixed the force-push notification. I think we can go ahead now.

**Pull request merged**
