### PR TITLE
 fixed most of vulnerabilities with NPM audit fix

### PR DESCRIPTION
**Pull request by maqboolkhan**
I used `npm audit fix` command to fix vulnerabilities. It fixed every vulnerability except two and these are from Angular packages (Dev dependencies).
`npm audit fix` updated bunch of packages so I tested UI with data set loading & bar chart creation, fortunately, everything working flawlessly.

### CODE REVIEW

**Comment by nikit91** [comment]
@maqboolkhan is there anybody in the team that could perform manual test for verification? (possibly someone from the new team members, as it might help them understand the functionality)

**Comment by maqboolkhan** [comment]
@RahulSherikar @nandeeshpatelgp please pull this branch and run IDA and perform UI operations with IDA chat bot & if everything works or anything breaks just comment here.
As Nikit said its a good opportunity to learn how IDA works.
Thanks

**Comment by RahulSherikar** [comment]
> @RahulSherikar @nandeeshpatelgp please pull this branch and run IDA and perform UI operations with IDA chat bot & if everything works or anything breaks just comment here.
> As Nikit said its a good opportunity to learn how IDA works.
> Thanks

Sure will do, Thanks

**Comment by RahulSherikar** [comment]
> @RahulSherikar @nandeeshpatelgp please pull this branch and run IDA and perform UI operations with IDA chat bot & if everything works or anything breaks just comment here.
> As Nikit said its a good opportunity to learn how IDA works.
> Thanks

Hi Maq,
Followed your sent instructions to chat with the chatbot to perform below things, since the chatbot understands only a few sets of instructions,
1. Load dataset query 
2. Requesting BarGraph
3. Requesting Force-Directed Graph
4. Clustering

found no issues in points 1,2 and 3 but I'm getting some kind of error for point 4 and the clustering is not getting plotted as shown below
IDA Clustering error

Still will explore into the chatbot to understand how it works and so on.

Thanks.

**Pull request merged**
